name: Release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  
  workflow_dispatch:

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        
      - name: Zip Chromium
        uses: thedoctor0/zip-release@main
        id: chrome-zip
        with: 
          type: zip
          filename: chromium.zip
          directory: chromium
          exclusions: '*.md*'  
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v0.1.2"
         
          artifacts: "chromium/chromium.zip"
          body: |
            authifyNow should be compatible with all chromium based browsers. (Brave, Vivaldi, Edge, Chrome, Opera)
            
            Chrome Store: [Download ](https://chrome.google.com/webstore/detail/authifynow/ogmhhgdbeabejjnhpdojnkkfhkklicln)
            Mozilla Store: [Download](https://addons.mozilla.org/en-US/firefox/addon/authifynow/)
            
            
               
          draft: true
          name: " authifyNow v0.1.4"
          generateReleaseNotes: true
          makeLatest: true
          
